version: '3'

volumes:
  postgres-db-volume:

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: exp
      POSTGRES_USER: exp
      POSTGRES_PASSWORD: exp
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --locale=C
    ports:
      - 15432:5432
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
